### ISSUE TITLE
IOS Safari Navbar Dropdown Bug

### ISSUE THREAD

**Issue by shortxmas** [8bitUHM/compscihi#31]
I'm not entirely sure if its just me but going to https://compscihi.com on my iPhone safari browser, the dropdowns for navbar and profile don't work. If I go into incognito, it works upon initial load but after a refresh or any navigation to another page, it breaks.
I would investigate this by trying to replicate on Safari and looking at dev tools.

**Comment by LeviKuhaulua** [comment]
can confirm and replicate issue for both iphone and ipad. **See notes below.**

iPhone & iPad: 
1. Dropdowns for profile and navbar work on initial load (both incognito mode and regular) however, it doesn't work after refreshing the page or after navigating to another page.
2. Additionally, if you close the tab then attempt to go back to the [compscihi](https://compscihi.com) website, the dropdown menu will not work. 
3. Opportunities page, if you try to click on the `order`, `sort`, or `filter` dropdown, it will not appear either. It may be similar work on initial load but so far I was unable to get it working when trying to debug on my iphone and safari (both the website and local host)
4. Last thing, to isolate the issue, I went over to Google Chrome on my iphone and was also able to replicate the issue. Same situation happens on Google Chrome. 

Clearing Cache: 
- After clearing cache for both ipad and iphone then going back to the website, the issue was still the same with it working on initial load then not working after refreshing page or navigating to another page.
